ifeq ($(config),debug)
    CXXFLAGS += -pthread -std=c++11 -I../.. -I../../.. -L../lib -L../../lib -L$(shell llvm-config --libdir) -g -O0
else
    CXXFLAGS += -pthread -std=c++11 -I../.. -I../../.. -L../lib -L../../lib -L$(shell llvm-config --libdir) -DNDEBUG -O3
endif

